config/routes.rb
Rails.application.routes.draw do
  get "/" => "homes#top", as: "top"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update, :index] do
    get :search, on: :collection
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: [:index]
  delete "notifications" => "notifications#destroy_all", as: "user_notifications_destroy_all"

  resources :groups do
    get "join" => "groups#join"
  end

  resources :messages, only: [:show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy
  validates :comment, presence: true, length: { maximum: 500 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  # 1人が１つの投稿に対して、１つしかいいねをつけられないようにする
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 1000 }
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :message, presence: true, length: { maximum: 500 }
end

app/models/notification.rb
class Notification < ApplicationRecord
  # スコープ(新着順)
  default_scope-> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true # option: trueでpost_idにnillを許容する
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  attachment :image
  # いいね済みか判断する
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # タグ付け機能
  acts_as_taggable

  # 日付の制限
  def date_is_valid?
    errors.add(:date, "が無効な日付です") if date.present? && date > Date.today
  end

  # 通知機能（いいね）
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(post_id: id, visited_id: user_id, kind: "favorite")
    notification.save if notification.valid?
  end

  # 通知機能（コメント）
  def create_notification_comment!(current_user, comment_id)
    # 自分以外のコメントしている人を全て取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct # distinctメソッドで、重複レコードを1つにまとめる
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # 誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # 一つの投稿に対して複数回通知をする
    notification = current_user.active_notifications.new(post_id: id, comment_id: comment_id, visited_id: visited_id, kind: 'comment')
    # 自分の投稿に対するコメントを通知済みにする
    if notification.visiter_id == notification.visited_id
      notification.check = true
    end
    notification.save if notification.valid?
  end

  validates :title, presence: true, length: { maximum: 20 }
  validates :image, presence: true
  validate :date_is_valid?
  validates :content, length: { maximum: 1000 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :comments, dependent: :destroy

  has_many :active_relationships,  class_name:  "Relationship", foreign_key: "follower_id", dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed # 自分がフォローしている人
  has_many :followers, through: :passive_relationships, source: :follower # 自分をフォローしている人

  # 通知機能
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy


  # DM機能
  has_many :entries
  has_many :messages
  has_many :rooms, through: :entries

  # フォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # フォローを外す
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # フォローしているか確認
  def following?(other_user)
    following.include?(other_user)
  end

  # 誕生日の制限
  def birthday_is_valid?
    errors.add(:birthday, "が無効な日付です。") if birthday.nil? || birthday > Date.today
  end

  # ユーザー検索
  def self.search(keyword)
    where(["name like? OR nickname like?", "%#{keyword}%", "%#{keyword}%"])
  end

  # 通知機能（フォロー）
  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and kind = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(visited_id: id, kind: 'follow')
      notification.save if notification.valid?
    end
  end

  validates :name, presence: true, length: { maximum: 20 }
  validates :nickname, { presence: true, uniqueness: true, length: { maximum: 20 } }
  validate :birthday_is_valid?
  validates :introduction, length: { maximum: 150 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :baria_user, only: [:destroy]
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    @comment_post = @comment.post
    if @comment.save
      @comment_post.create_notification_comment!(current_user, @comment.id)
    else
      render:error # render先にjsファイルを指定
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

  def baria_user
    if current_user.nil? || Comment.find(params[:id]).user.id.to_i != current_user.id
      flash[:alert] = "権限がありません。"
      redirect_to post_path(@post)
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<hr>
<div class="comments card-text">
  <h4 class="mt-3"><%= post.comments.count %>件のコメント</h4>
  <% post.comments.each do |comment| %>
    <p class="text-right mb-0"><%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></p>
    <div class="comment-box mb-3">
      <div class="row">
        <div class="col-xxl-2 col-lg-3 col-sm-2 col-3 px-0 ml-sm-0 ml-1 text-center">
          <%= link_to user_path(comment.user) do %>
            <%= attachment_image_tag comment.user, :profile_image, :fill, 70, 70, fallback: "no_profile_image.jpg", class:"profile-image mt-3 rounded-circle"%></br>
          <% end %>
        </div>
        <div class="col-xxl-10 col-lg-9 col-sm-10 col-8 px-0 py-2 pr-4">
          <div class="username my-3"><%= comment.user.nickname %></div>
          <p><%= comment.comment %></p>
          <% if comment.user == current_user %>
            <div class="text-right mr-3">
              <%= link_to post_comment_path(comment.post, comment), id: 'delete-' + comment.id.to_s + '-btn', method: :delete, remote: true do %>
                <span class="trash">
                  <span></span>
                  <i></i>
                </span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<hr>
<div class="new-comment card-text">
  <%= form_with(model:[post, Comment.new], remote: true) do |f| %>
    <div id="comments-error">
      <%= render 'layouts/error_messages', model: f.object %>
    </div>
    <div class="form-group">
      <div class="comment-field">
        <%= f.label :コメント %><br />
        <%= f.text_area :comment, rows:'5', class: "form-control", id: "comment_form", placeholder: "500文字以内" %>
      </div>
      <div class="comment-action">
        <%= f.submit "コメントを送る" %>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_comments.html.erb
<hr>
<div class="comments card-text">
  <h4 class="mt-3"><%= post.comments.count %>件コメント</h4>
  <% post.comments.each do |comment| %>
    <div class="media border mb-3">
      <%= attachment_image_tag comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"bd-placeholder-img align-self-center mx-3" %>
      <div class="media-body ml-4 p-3">
        <p><%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %></p>
        <p><%= comment.comment %></p>
        <% if comment.user == current_user %>
          <%= link_to "削除", post_comment_path(comment.post, comment), method: :delete, class: "btn btn-danger pull-right" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<hr>
<div class="new-comment card-text">
  <%= form_with(model:[post, comment]) do |f| %>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">コメントする</label>
      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
    </div>
    <%= f.submit "送信する", class:"btn btn-lg btn-info mt-2 float-right" %>
  <% end %>
</div>

app/views/comments/create.js.erb
$("#comment_<%= @post.id %> .comment-show").html("<%= j(render 'comments/comment', post: @post, comment: @comment ) %>");
$("#comment_form").val("");
<!--フラッシュメッセージの非同期通信化-->
$('#flash-message').html("<%= j(render 'layouts/flash_messages') %>");

app/views/comments/destroy.js.erb
$("#comment_<%= @post.id %> .comment-show").html("<%= j(render 'comments/comment', post: @post, comment: @comment ) %>");
$("#comment_form").val("");
$('#flash-message').html("<%= j(render 'layouts/flash_messages') %>");

app/views/comments/error.js.erb
$("#comments-error").html("<%= j(render 'layouts/error_messages', model: @comment) %>");