config/routes.rb
Rails.application.routes.draw do
  get "/" => "homes#top", as: "top"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update, :index] do
    get :search, on: :collection
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: [:index]
  delete "notifications" => "notifications#destroy_all", as: "user_notifications_destroy_all"

  resources :groups do
    get "join" => "groups#join"
  end

  resources :messages, only: [:show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy
  validates :comment, presence: true, length: { maximum: 500 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  # 1人が１つの投稿に対して、１つしかいいねをつけられないようにする
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 1000 }
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :message, presence: true, length: { maximum: 500 }
end

app/models/notification.rb
class Notification < ApplicationRecord
  # スコープ(新着順)
  default_scope-> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true # option: trueでpost_idにnillを許容する
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  attachment :image
  # いいね済みか判断する
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # タグ付け機能
  acts_as_taggable

  # 日付の制限
  def date_is_valid?
    errors.add(:date, "が無効な日付です") if date.present? && date > Date.today
  end

  # 通知機能（いいね）
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(post_id: id, visited_id: user_id, kind: "favorite")
    notification.save if notification.valid?
  end

  # 通知機能（コメント）
  def create_notification_comment!(current_user, comment_id)
    # 自分以外のコメントしている人を全て取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct # distinctメソッドで、重複レコードを1つにまとめる
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # 誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # 一つの投稿に対して複数回通知をする
    notification = current_user.active_notifications.new(post_id: id, comment_id: comment_id, visited_id: visited_id, kind: 'comment')
    # 自分の投稿に対するコメントを通知済みにする
    if notification.visiter_id == notification.visited_id
      notification.check = true
    end
    notification.save if notification.valid?
  end

  validates :title, presence: true, length: { maximum: 20 }
  validates :image, presence: true
  validate :date_is_valid?
  validates :content, length: { maximum: 1000 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :comments, dependent: :destroy

  has_many :active_relationships,  class_name:  "Relationship", foreign_key: "follower_id", dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed # 自分がフォローしている人
  has_many :followers, through: :passive_relationships, source: :follower # 自分をフォローしている人

  # 通知機能
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy


  # DM機能
  has_many :entries
  has_many :messages
  has_many :rooms, through: :entries

  # フォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # フォローを外す
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # フォローしているか確認
  def following?(other_user)
    following.include?(other_user)
  end

  # 誕生日の制限
  def birthday_is_valid?
    errors.add(:birthday, "が無効な日付です。") if birthday.nil? || birthday > Date.today
  end

  # ユーザー検索
  def self.search(keyword)
    where(["name like? OR nickname like?", "%#{keyword}%", "%#{keyword}%"])
  end

  # 通知機能（フォロー）
  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and kind = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(visited_id: id, kind: 'follow')
      notification.save if notification.valid?
    end
  end

  validates :name, presence: true, length: { maximum: 20 }
  validates :nickname, { presence: true, uniqueness: true, length: { maximum: 20 } }
  validate :birthday_is_valid?
  validates :introduction, length: { maximum: 150 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to  groups_path
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
    redirect_to groups_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_group_form.html.erb
<div class="group-field" id="group-text">
  <%= f.label :グループ名 %><span Class="group-required">必須</span><br />
  <%= f.text_field :name, autofocus: true, autocomplete: "title", placeholder: "20文字以内"  %>
</div>
<div class="group-field" id="group-text">
  <%= f.label :紹介文 %><br />
  <%= f.text_area :introduction, autocomplete: "content", placeholder: "1000文字以内" %>
</div>
<div class="group-field" id="field-image">
  <%= f.label :グループ画像 %><br />
  <%= attachment_image_tag group, :image, fallback: "no_image.jpg" %>
  <%= f.attachment_field :image %>
</div>

app/views/groups/edit.html.erb
<div class="group-container">
  <div class="group-contents">
    <h1>Edit Group</h1>
    <div class="group-form">
      <%= form_with model: @group, local:true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <%= render "groups/group_form", group: @group, f: f %>
        <span class="group-action">
          <%= f.submit '更新する' %>
        </span>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="group-container">
  <div class="groups-contents">
    <h1>Groups</h1>
    <div class="group-form">
      <hr>
      <% if @groups.present? %>
        <% @groups.each do |group| %>
          <div class="container">
            <div class="row">
              <div class="col-xl-2 col-md-3 col-3 text-left ml-md-0 px-0 ml-1">
                <%= link_to group_path(group) do %>
                  <%= attachment_image_tag group, :image, fallback: "no_image.jpg", class:"groups-image mt-3"; %><br>
                <% end %>
              </div>
              <div class="col-xl-10 col-md-9 col-8 text-left px-0">
                <div class="row">
                  <div class="col-xl-10 col-md-10 col-8 text-left px-0 mt-3">
                    <%= link_to group_path(group) do %>
                      <h2><%= group.name %></h2>
                    <% end %>
                  </div>
                  <div class="group-btn col-md-2 col-3 mr-md-0 mr-1 mt-3">
                    <% if group.owner_id == current_user.id %>
                      <div id="edit-btn">
                        <%= link_to 'Edit', edit_group_path(group) %>
                      </div>
                    <% elsif group.users.include?(current_user) %>
                      <div id="leave-btn">
                        <%= link_to 'Leave', group_path(group), method: :delete %>
                      </div>
                    <% else %>
                      <div id="join-btn">
                        <%= link_to 'Join', group_join_path(group) %>
                      </div>
                    <% end %>
                  </div>
                </div>
                <div class="row" id="groups-counts">
                 <h7>users : <%= group.users.count %>&emsp;</h7>
                </div>
                <div class="user-introduction row mr-md-0 mr-md-0 mr-1">
                  <h7><%= group.introduction %></h7>
                </div>
              </div>
            </div>
          </div>
          <hr>
        <% end %>
      <% else %>
        <h4 class="mt-5">グループはありません</h4>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="group-container">
  <div class="group-contents">
    <h1>Create Group</h1>
    <div class="group-form">
      <%= form_with model: @group, local:true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <%= render "groups/group_form", group: @group, f: f %>
        <span class="group-action">
          <%= f.submit '作成する' %>
        </span>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="group-container">
  <div class="follow-contents">
    <h1><%= @group.name %></h1>
    <div class="group-form">
      <div class="row">
        <div class="col-5 text-left pl-0">
          <%= attachment_image_tag @group, :image, :fill, 100, 100, fallback: "no_image.jpg", class:"group-image"; %>
        </div>
        <div class="col-7 pr-0">
          <div class="row">
            <div class="col-10">
              <div class="row">
                <h2>紹介</h2>
              </div>
            </div>
            <div class="col-2">
              <div class="group-btn">
                <% if @group.owner_id == current_user.id %>
                  <div id="edit-btn">
                    <%= link_to 'Edit', edit_group_path(@group) %>
                  </div>
                <% elsif @group.users.include?(current_user) %>
                  <div id="leave-btn">
                    <%= link_to 'Leave', group_path(@group), method: :delete %>
                  </div>
                <% else %>
                  <div id="join-btn">
                    <%= link_to 'Join', group_join_path(@group) %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="row user-introduction text-left mt-3">
            <h7><%= @group.introduction %></h7>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="mt-5">
          <h3>メンバー（<%= @group.users.count %>名）</h3>
        </div>
      </div>
      <div>
      <hr>
        <% @group.users.each do |member| %>
          <div class="row">
            <div class="col-xl-2 col-md-3 col-3 text-left ml-md-0 px-0 ml-1">
              <%= link_to user_path(member) do %>
                <%= attachment_image_tag member, :profile_image, :fill, 100, 100, fallback: "no_profile_image.jpg", class:"profile-image mt-3 rounded-circle"; %><br>
              <% end %>
            </div>
            <div class="col-xl-10 col-md-9 col-8 text-left px-0">
              <div class="row">
                <div class="col-xl-10 col-md-9 col-8 text-left px-0 mt-3">
                  <%= link_to user_path(member) do %>
                    <h2 class="username-show"><%= member.nickname %></h2>
                  <% end %>
                </div>
                <div class="col-xl-2 col-md-3 col-3 mr-md-0 mr-1 mt-3">
                  <div class="follow_<%= member.id %>" id="follow">
                    <span class="group_follow_form">
                      <span class="follow_form" >
                        <%= render 'relationships/follow_form', user: member %>
                      </span>
                    </span>
                  </div>
                </div>
              </div>
              <div class="user-introduction row mr-md-0 mr-md-0 mr-1">
                <h7><%= member.introduction %></h7>
              </div>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>