config/routes.rb
Rails.application.routes.draw do
  get "/" => "homes#top", as: "top"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update, :index] do
    get :search, on: :collection
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: [:index]
  delete "notifications" => "notifications#destroy_all", as: "user_notifications_destroy_all"

  resources :groups do
    get "join" => "groups#join"
  end

  resources :messages, only: [:show, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :comments, dependent: :destroy

  has_many :active_relationships,  class_name:  "Relationship", foreign_key: "follower_id", dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed # 自分がフォローしている人
  has_many :followers, through: :passive_relationships, source: :follower # 自分をフォローしている人

  # 通知機能
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy


  # DM機能
  has_many :entries
  has_many :messages
  has_many :rooms, through: :entries

  # フォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # フォローを外す
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # フォローしているか確認
  def following?(other_user)
    following.include?(other_user)
  end

  # 誕生日の制限
  def birthday_is_valid?
    errors.add(:birthday, "が無効な日付です。") if birthday.nil? || birthday > Date.today
  end

  # ユーザー検索
  def self.search(keyword)
    where(["name like? OR nickname like?", "%#{keyword}%", "%#{keyword}%"])
  end

  # 通知機能（フォロー）
  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and kind = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(visited_id: id, kind: 'follow')
      notification.save if notification.valid?
    end
  end

  validates :name, presence: true, length: { maximum: 20 }
  validates :nickname, { presence: true, uniqueness: true, length: { maximum: 20 } }
  validate :birthday_is_valid?
  validates :introduction, length: { maximum: 150 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
    # 非公開記事の制限
    if @user != current_user
      @posts = Post.where(status: false, user_id: @user.id)
    end

    # タグで絞り込む
    if params[:tag_name]
      @posts = Post.tagged_with(params[:tag_name])
    end
  end

  def index
    # 自分以外のユーザー一覧を表示
    @users = User.where.not(id: current_user.id).order(id: "DESC") # idの降順
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "プロフィールを更新しました。"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following
    render 'follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'follow'
  end

  def search
    # 自分以外のユーザーを検索
    @users = User.search(params[:keyword]).where.not(id: current_user.id).order(id: "DESC") # idの降順
    @keyword = params[:keyword]
    render "index"
  end

  private

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :birthday, :profile_image, :introduction)
  end

  # 編集、削除の権限を投稿者だけの機能にする
  def baria_user
    if current_user.nil? || User.find(params[:id]).id.to_i != current_user.id
      flash[:alert] = "権限がありません。"
      redirect_to top_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_calendar.html.erb
<div id="calendar"></div>
    <script>
      $(document).ready(function() {
  $("#calendar").fullCalendar({

    header: {
      left: '',
      center: 'today prev,next',
      right: 'title',
    },

    buttonText: {
      prev: '前',
      next: '次',
      today: '今日',
      month: '月',
      week: '週',
      day: '日'
    },

    events: "/users/<%= @user.id %>",

    //イベントの色を変える
    eventColor: 'orange',
    //イベントの文字色を変える
    eventTextColor: 'white',
    //カレンダー上部を年月で表示させる
    titleFormat: 'YYYY年 M月',
    //曜日を日本語表示
    dayNamesShort: ['日', '月', '火', '水', '木', '金', '土'],
    //ボタンのレイアウト
    color: 'yellow',
    textColor: 'black',
     navLinks: false,
    select: function(date) {
      $('#new_post').modal('show');
    }

  })
});
    </script>

app/views/users/edit.html.erb
<div class="user-container">
  <div class="user-contents">
    <h1>Edit</h1>
    <div class="user-form">
      <%= form_with model:@user, local:true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="user-field">
          <%= f.label :氏名 %><span Class="required-orange">必須</span><br />
          <%= f.text_field :name, autofocus: true, autocomplete: "title" %>
        </div>
        <div class="user-field">
          <%= f.label :ニックネーム %><span Class="required-orange">必須</span><br />
          <%= f.text_field :nickname, autocomplete: "nickname" %>
        </div>
        <div class="user-field">
          <%= f.label :メールアドレス %><span Class="required-orange">必須</span><br />
          <%= f.email_field :email, autocomplete: "email" %>
        </div>
        <div class="user-field" id="birthday">
          <%= f.label :生年月日 %><span Class="required-orange">必須</span><br />
          <%= raw sprintf(f.date_select(:birthday, use_month_numbers: true, start_year: 1900, end_year: Time.now.year, default: Date.new(2000, 1, 1), date_separator: '%s'),'&nbsp;年&emsp;', '&nbsp;月&emsp;') + '&nbsp;日' %>
        </div>
        <div class="post-field" id="profile">
          <%= f.label :プロフィール画像 %><br />
          <%= attachment_image_tag @user, :profile_image, :fill, 75, 75, fallback: "no_profile_image.jpg", class:"profile-image mt-3 rounded-circle"; %><br />
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        </div>
        <div class="post-field" id="introduction">
          <%= f.label :自己紹介 %><br />
          <%= f.text_area :introduction, autocomplete: "introduction", placeholder: "150字以内で自由に記述してください" %>
        </div>
        <span class="user-action">
          <%= f.submit "更新する" %>
         </span>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follow.html.erb
<div class="follow-container">
  <div class="follow-contents">
    <h1><%= @user.nickname %></h1>
    <h1><%= @title %></h1>
    <div class="follow-index">
      <hr>
      <% if @users.present? %>
        <% @users.each do |user| %>
          <div class="container">
            <div class="row">
              <div class="col-xl-2 col-md-3 col-3 text-left ml-md-0 px-0 ml-1">
                <%= link_to user_path(user) do %>
                  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_profile_image.jpg", class:"profile-image mt-3 rounded-circle"; %>
                <% end %>
              </div>
              <div class="col-xl-10 col-md-9 col-8 text-left px-0">
                <div class="row">
                  <div class="col-lg-10 col-md-9 col-8 text-left mt-3">
                    <div class="row">
                      <%= link_to user_path(user) do %>
                        <h2><%= user.nickname %></h2>
                      <% end %>
                    </div>
                    <div class="row" id="posts-count">
                      <h6>posts : <%= user.posts.count %></h6>
                    </div>
                  </div>
                  <div class="col-lg-2 col-md-3 col-3 mt-3">
                    <div class="follow_<%= user.id %>">
                      <span class="index_follow_form">
                        <span class="follow_form" >
                          <%= render 'relationships/follow_form', user: user %>
                        </span>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="row text-left mr-md-0 mr-1">
                  <h7 class="user-introduction"><%= user.introduction %></h7>
                </div>
              </div>
            </div>
          </div>
          <hr>
        <% end %>
      <% else %>
        <h4 class="mt-5">ユーザーはいません。</h4>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="follow-container">
  <div class="users-contents">
    <h1>Users</h1>
    <div class="search-form">
      <%= form_with url: search_users_path, method: :get, local: true do |f| %>
        <span class="search_title">
          <%= f.text_field :keyword, value: @keyword, placeholder: "ユーザー検索", style: "border: none" %>
        </span>
        <span class="search_action">
          <%= button_tag sanitize('<i class="fa fa-search"></i>'), :type => "submit" %>
        </span>
      <% end %>
    </div>
    <div class="follow-index">
      <hr>
      <% if @users.present? %>
        <% @users.each do |user| %>
          <div class="container">
            <div class="row">
              <div class="col-xl-2 col-md-3 col-3 text-left ml-md-0 px-0 ml-1">
                <%= link_to user_path(user) do %>
                  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_profile_image.jpg", class:"profile-image mt-3 rounded-circle"; %><br>
                <% end %>
                <span id="users-counts-responsive">
                  <h7>posts : <%= user.posts.count %></h7><br>
                  <span class="follow_<%= user.id %>">
                    <h7>following : </h7>
                    <span class="following-count">
                      <%= link_to following_user_path(user) do %>
                        <h7><%= user.following.count %></h7><br>
                      <% end %>
                    </span>
                    <h7>followers : </h7>
                    <span class="followers-count">
                      <%= link_to followers_user_path(user) do %>
                        <h7><%= user.followers.count %></h7>
                      <% end %>
                    </span>
                  </span>
                </span>
              </div>
              <div class="col-xl-10 col-md-9 col-8 text-left px-0">
                <div class="row">
                  <div class="col-xl-10 col-md-9 col-8 text-left px-0 mt-3">
                    <%= link_to user_path(user) do %>
                      <h2 class="username-show"><%= user.name %><br>(<%= user.nickname %>)</h2>
                    <% end %>
                  </div>
                  <div class="col-xl-2 col-md-3 col-3 mr-md-0 mr-1 mt-3">
                    <div class="follow_<%= user.id %>" id="follow">
                      <span class="index_follow_form">
                        <span class="follow_form" >
                          <%= render 'relationships/follow_form', user: user %>
                        </span>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="row" id="users-counts">
                 <h7>posts : <%= user.posts.count %>&emsp;</h7>
                  <span class="follow_<%= user.id %>">
                    <h7>following : </h7>
                    <span class="following-count">
                      <%= link_to following_user_path(user) do %>
                        <h7><%= user.following.count %>&emsp;</h7>
                      <% end %>
                    </span>
                    <h7>followers : </h7>
                    <span class="followers-count">
                      <%= link_to followers_user_path(user) do %>
                        <h7><%= user.followers.count %></h7>
                      <% end %>
                    </span>
                  </span>
                </div>
                <div class="user-introduction row mr-md-0 mr-md-0 mr-1">
                  <h7><%= user.introduction %></h7>
                </div>
              </div>
            </div>
          </div>
          <hr>
        <% end %>
      <% else %>
        <h4 class="mt-5">ユーザーはいません</h4>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="containar">
  <div class="flash-message" id="flash-message-user">
    <%= render 'layouts/flash_messages' %>
  </div>
  <div id="userpage-title">
    <% if current_user.present? && (@user.id == current_user.id) %>
      <h1>My page</h1>
    <% else %>
      <h1><%= @user.nickname %></h1>
    <% end %>
  </div>
  <div class="row mb-xl-5 mb-0">
    <div class="col-xl-6 px-sm-3 px-2">
      <div class="user-show-containar mx-sm-5 mx-0" >
        <div class="card mx-auto">
          <header class="users-header">
            <div id="message-link">
              <% if current_user != @user and current_user.following?(@user) %>
                <%= link_to message_path(@user.id) do %>
                  <i class="far fa-envelope"></i>
                <% end %>
              <% end %>
            </div>
            <div class="avatar">
              <%= attachment_image_tag @user, :profile_image, :fill, 150, 150, fallback: "no_profile_image.jpg" %>
            </div>
          </header>
          <h3><%= @user.nickname %></h3>
          <span class="birthday">
            <i class="fas fa-birthday-cake"></i>&nbsp;&nbsp;<%= @user.birthday.strftime("%-m月%-d日") %>
          </span>
          <div class="desc">
            <%= @user.introduction %>
          </div>
          <div class="counts">
            <span class="follow_<%= @user.id %>">
            <ul>
              <li>
                <span><%= @user.posts.count %></span>
                <p>posts</p>
              </li>
              <li>
                <span class="following-count">
                  <%= link_to following_user_path(@user) do %>
                    <%= @user.following.count %>
                  <% end %>
                </span>
                <p>following</p>
              </li>
              <li>
                <span class="followers-count">
                  <%= link_to followers_user_path(@user) do %>
                    <%= @user.followers.count %>
                  <% end %>
                </span>
                <p>followers</p>
              </li>
            </ul>
            </span>
          </div>
          <% if current_user.present? && (@user.id == current_user.id) %>
            <span class="follow_footer_a">
              <footer class="users-footer", id="footer-mypage">
                <%= link_to "プロフィール編集", edit_user_path(@user) %>
              </footer>
            </span>
          <% elsif current_user.present? && (@user.id != current_user.id) %>
            <div class="follow_<%= @user.id %>">
              <div class="follow_footer_a mb-5">
                <span class="follow_form" ><%= render 'relationships/follow_form', user: @user %></span>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xl-6 px-0">
      <%= render "calendar" %>
    </div>
  </div>
  <div class="col">
    <h3 class="users-show-post">posts</h3>
    <%= render "posts/post_index", posts: @posts %>
  </div>
</div>