config/routes.rb
Rails.application.routes.draw do
  get "/" => "homes#top", as: "top"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update, :index] do
    get :search, on: :collection
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: [:index]
  delete "notifications" => "notifications#destroy_all", as: "user_notifications_destroy_all"

  resources :groups do
    get "join" => "groups#join"
  end

  resources :messages, only: [:show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy
  validates :comment, presence: true, length: { maximum: 500 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  # 1人が１つの投稿に対して、１つしかいいねをつけられないようにする
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 1000 }
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :message, presence: true, length: { maximum: 500 }
end

app/models/notification.rb
class Notification < ApplicationRecord
  # スコープ(新着順)
  default_scope-> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true # option: trueでpost_idにnillを許容する
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  attachment :image
  # いいね済みか判断する
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # タグ付け機能
  acts_as_taggable

  # 日付の制限
  def date_is_valid?
    errors.add(:date, "が無効な日付です") if date.present? && date > Date.today
  end

  # 通知機能（いいね）
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(post_id: id, visited_id: user_id, kind: "favorite")
    notification.save if notification.valid?
  end

  # 通知機能（コメント）
  def create_notification_comment!(current_user, comment_id)
    # 自分以外のコメントしている人を全て取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct # distinctメソッドで、重複レコードを1つにまとめる
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # 誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # 一つの投稿に対して複数回通知をする
    notification = current_user.active_notifications.new(post_id: id, comment_id: comment_id, visited_id: visited_id, kind: 'comment')
    # 自分の投稿に対するコメントを通知済みにする
    if notification.visiter_id == notification.visited_id
      notification.check = true
    end
    notification.save if notification.valid?
  end

  validates :title, presence: true, length: { maximum: 20 }
  validates :image, presence: true
  validate :date_is_valid?
  validates :content, length: { maximum: 1000 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :comments, dependent: :destroy

  has_many :active_relationships,  class_name:  "Relationship", foreign_key: "follower_id", dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed # 自分がフォローしている人
  has_many :followers, through: :passive_relationships, source: :follower # 自分をフォローしている人

  # 通知機能
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy


  # DM機能
  has_many :entries
  has_many :messages
  has_many :rooms, through: :entries

  # フォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # フォローを外す
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # フォローしているか確認
  def following?(other_user)
    following.include?(other_user)
  end

  # 誕生日の制限
  def birthday_is_valid?
    errors.add(:birthday, "が無効な日付です。") if birthday.nil? || birthday > Date.today
  end

  # ユーザー検索
  def self.search(keyword)
    where(["name like? OR nickname like?", "%#{keyword}%", "%#{keyword}%"])
  end

  # 通知機能（フォロー）
  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and kind = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(visited_id: id, kind: 'follow')
      notification.save if notification.valid?
    end
  end

  validates :name, presence: true, length: { maximum: 20 }
  validates :nickname, { presence: true, uniqueness: true, length: { maximum: 20 } }
  validate :birthday_is_valid?
  validates :introduction, length: { maximum: 150 }
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <h5><%= model.errors.count %>件のエラー</h5>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if flash[:notice] %>
  <div class="flash-message">
    <p id='notice'><%= flash[:notice]%></p>
  </div>
<% elsif flash[:alert]%>
  <div class="flash-message">
    <p id='alert'><%= flash[:alert] %></p>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="align-middle">
  <p class="text-center mx-auto" style="margin-bottom: 0;">©︎ 2021 Travel Records.com</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <span id="header">
    <nav class="navbar navbar-expand fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/"><%= image_tag "logo.png", class: "logoimage" %></a>
        <% if user_signed_in? %>
          <ul class="navbar-nav mt-md-3 mt-1">
            <li class="nav-item">
              <%= link_to "/#about-visual", class: 'nav-link' do %>
                <div class="icon effect blue">
                  <i class="far fa-question-circle"></i>
                </div>
                <p class="link-text">このサイトについて</p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to posts_path, class: 'nav-link' do %>
                <div class="icon effect green">
                  <i class="fas fa-stream"></i>
                </div>
                <p class="link-text">タイムライン</p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_post_path, class: 'nav-link' do %>
                <div class="icon effect pink">
                  <i class="far fa-plus-square"></i>
                </div>
                <p class="link-text">新規投稿</p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link' do %>
                <div class="icon effect yellow">
                  <i class="fas fa-user-circle"></i>
                </div>
                <p class="link-text">マイページ</p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path(current_user.id), class: 'nav-link' do %>
                <div class="icon effect purple">
                  <i class="fas fa-users"></i>
                </div>
                <p class="link-text">ユーザー</p>
              <% end %>
            </li>
          </ul>
          <ul class="nav_right">
            <li class="nav-item2" id="nav_right_1">
              <%= link_to notifications_path, class: "nav-link" do %>
                <% if uncheck_notifications.any? %>
                  <i class="fas fa-exclamation-circle" style="color: gold;"></i>
                <% else %>
                  <i class="fas fa-exclamation-circle"></i>
                <% end %>
                <spna> &emsp;通知</span>
              <% end %>
            </li>
            <li class="nav-item2" id="nav_right_2">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
                <i class="fas fa-sign-out-alt"></i>
                <span> &emsp;ログアウト</span>
              <% end %>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav ml-auto mt-md-3 mt-1">
            <li class="nav-item">
              <%= link_to "/#about-visual", class: 'nav-link' do %>
                <div class="icon effect blue">
                  <i class="far fa-question-circle"></i>
                </div>
                <p class="link-text">このサイトについて</p>
              <% end %>
            </li>
          </ul>
          <ul class="nav_right">
            <li class="nav-item2" id="nav_right_1">
              <%= link_to new_user_registration_path, class: 'nav-link' do %>
                <i class="fas fa-user-plus"></i>
                <spna> &emsp;新規登録</span>
              <% end %>
            </li>
            <li class="nav-item2" id="nav_right_2">
              <%= link_to new_user_session_path, class: 'nav-link' do %>
                <i class="fas fa-sign-in-alt"></i>
                <span> &emsp;ログイン</span>
              <% end %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
  </span>
  <span id="header-responsive">
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand py-0 fixed-top">
        <div class="container">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to posts_path, class: 'nav-link' do %>
                <div class="icon effect green">
                  <i class="fas fa-stream"></i>
                </div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_post_path, class: 'nav-link' do %>
                <div class="icon effect pink">
                  <i class="far fa-plus-square"></i>
                </div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link' do %>
                <div class="icon effect yellow">
                  <i class="fas fa-user-circle"></i>
               </div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path(current_user.id), class: 'nav-link' do %>
                <div class="icon effect purple">
                  <i class="fas fa-users"></i>
                </div>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
      <nav class="navbar fixed-top" id="menuebar">
        <!-- ハンバーガーメニュー -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- ナビゲーションメニュー -->
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item3 active">
              <a href="/" class='nav-link'><p>Top</p></a>
            </li>
            <hr>
            <li class="nav-item3">
              <%= link_to "/#about-visual", class: 'nav-link' do %>
                <p>About</p>
              <% end %>
            </li>
            <hr>
            <li class="nav-item3">
              <%= link_to notifications_path, class: "nav-link" do %>
                <% if uncheck_notifications.any? %>
                 <p>通知あり</p>
                <% else %>
                  <p>通知なし</p>
                <% end %>
              <% end %>
            </li>
            <hr>
            <li class="nav-item3">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
                <p>ログアウト</p>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
    <% else %>
      <ul class="navbar-nav mt-1 ml-1">
        <li>
          <h1><a class="navbar-brand" href="/"><%= image_tag "logo.png", class: "logoimage" %></a></h1>
        </li>
        <li class="nav-item" id="about">
          <%= link_to "/#about-visual", class: 'nav-link' do %>
            <div class="icon effect blue">
              <i class="far fa-question-circle"></i>
            </div>
          <% end %>
        </li>
      </ul>
      <ul class="nav_right">
        <li class="nav-item2" id="nav_right_1">
          <%= link_to new_user_registration_path, class: 'nav-link' do %>
            <i class="fas fa-user-plus"></i>
            <spna>&nbsp;新規登録</span>
          <% end %>
        </li>
        <li class="nav-item2" id="nav_right_2">
          <%= link_to new_user_session_path, class: 'nav-link' do %>
            <i class="fas fa-sign-in-alt"></i>
            <span>&nbsp;ログイン</span>
          <% end %>
        </li>
      </ul>
    <% end %>
  </span>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="ja">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>TravelRecords</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/a385a89815.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a385a89815.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--カレンダー機能-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.css">
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>

</html>